# Generated by Django 5.1.7 on 2025-03-24 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('date', 'Date Night'), ('ex', 'Ex Files'), ('fun', 'Love & Laughs'), ('intimate', 'The Intimate Edit')], max_length=20)),
                ('intro', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('is_premium', models.BooleanField(default=False)),
            ],
        ),
    ]
